### ISSUE TITLE
Fails to update when manga name contains a single quote in the id

### ISSUE THREAD

**Issue by GDXN** [elliotcraft79/fmd_mangadex_converter#2]
This is an example of the generated query in witch it fails:

> UPDATE favorites SET id = 'd07c9c2425764da8ba056505f57cf40c/title/30b68b83-d8cd-46c2-ad6c-e2eca355ab36', link = '/title/30b68b83-d8cd-46c2-ad6c-e2eca355ab36', downloadedchapterlist = '/ad38f398-2bc7-468c-8b98-e82d541bf4d8
> /cc53ad4c-5b74-425d-a1c0-21021323ab25
> /c9ae4e16-792f-4cde-bdd7-6756c1961236
> /60a08367-b99b-47d8-aa6e-0bb082f61975
> /db314675-673c-493e-ab6b-bcfde7467658
> /b85e11b4-b560-4a4c-8266-b6836007bf8e
> /d87d7cee-bc74-4417-82c7-cd22c1c186dc
> ' WHERE id = 'd07c9c2425764da8ba056505f57cf40c/title/52507/deathbound duke's daughter and seven noblemen'

the quote in "duke's" is needs to be escaped for it to work, you need to make it two single quotes.

**Comment by elliotcraft79** [comment]
Should now be fixed
